export const tagIds = [
  "sages",
  "side_project",
  "university",
  "thesis",
  "cyfrowy_polsat",
  "it_run",

  "java",
  "kotlin",
  "sql",
  "scala",
  "python",
  "rust",
  "go",
  "c",
  "cpp",
  "pl_sql",
  "html",
  "css",
  "javascript",
  "typescript",
  "haskell",
  "prolog",
  "bash",
  "groovy",
  "ampl",
  "tex",
  "matlab",
  "assembly_x86",
  "assembly_mips",
  "makefile",

  "spring",
  "ktor",
  "helidon",
  "micronaut",
  "jsf",
  "prime_faces",
  "hibernate",
  "jakarta_ee",
  "jax_rs",
  "jakarta_cdi",
  "jboss_seam",
  "apache_hadoop",
  "axon",
  "android",
  "react_js",
  "astro_js",
  "django",
  "flask",

  "docker",
  "kubernetes",
  "ci_cd",
  "s3",
  "iac",

  "ddd",
  //   "tdd",
  "agile",
  "scrum",
  "kanban",
  //   "wcag",

  "rest_api",
  //   "graph_ql",
  "grpc",
  "cqrs",
  "event_sourcing",
  "dsl",

  "replication",
  "load_balancing",
  "circuit_breaker",
  "service_discovery",
  "service_registry",

  "basic_auth",
  "oauth2",
  "rbac",
  "otp",

  "ansible",
  "puppet",

  "gradle",
  "maven",
  "sbt",
  "node_js",

  "git",
  "github",
  "gitlab",
  "bitbucket",
  "jira",
  "trello",

  "jenkins",
  "github_actions",
  "bitbucket_pipelines",
  "gitlab_ci",
  "nginx",
  "apache",
  "certbot",
  "ssh",

  //   "wildfly"
  //   "jersey",
  //   "jetty",
  //   "netty",

  //   "ai",
  "chat_gpt",
  //   "open_ai",
  "gemini",
  "copilot",
  "rovo_dev",

  "vscode",
  "intellij",
  "pycharm",
  "go_land",
  "rust_rover",
  "c_lion",
  "data_grip",

  //   "figma",

  "keycloak",
  "liquibase",
  "sonar_qube",

  "ms_office",
  "libre_office",
  "google_workspace",

  "open_api",
  "swagger",

  "linux",
  "windows",
  "ubuntu",
  "wsl",

  "azure",
  "gcp",
  "oci",
  "ovh",

  //   "apache_active_mq",
  //   "apache_rabbit_mq",
  //   "apache_kafka",
  //   "apache_log4j",
  //   "slf4j",
  //   "logback",
  //   "apache_pdf_box",
  //   "apache_poi",
  //   "apache_solr",
  //   "apache_spark",
  //   "apache_flink",
  //   "apache_tika",
  //   "apache_tomcat",
  //   "apache_zookeeper",
  //   "bouncy_castle",
  //   "deep_java_library",
  //   "elastic_search",
  //   "google_gson",
  //   "google_guava",
  //   "jackson",
  //   "java_fx",
  //   "jaxb" - xml
  //   "open_cv",
  //   "quartz",
  //   "jetbrains_exposed",
  //   "cas", // Central Authentication Service
  //   "kotlin_arrow",
  //   "fuel",
  //   "hoplite",
  //   "apache_commons",
  //   "excel_kt",
  //   "simple_java_mail",
  //   "kotest",

  // "tailwind",
  // "expressive-code",
  // "playwright",
  // "polyglot",
  // "rehype",
  // "remark",

  "pandas",
  //   "py_spark",
  //   "py_torch",
  //   "keras",
  //   "num_py",
  //   "matplotlib"

  //   "junit",
  //   "mockito",
  //   "spock"

  //   "spring_boot",
  //   "spring_aop",
  //   "spring_data",
  //   "spring_security",
  //   "spring_cloud"

  //   "spring_mvc",
  //   "spring_webflux"

  "apache_hive",
  "mongo_db",
  "arango_db",
  "postgres",
  "oracle",
  "mysql",
  "mariadb",
  "sqlite",
  "redis",
  "ms_access",
  "firebase",
  "h2",

  "driving",
  "driving_am",
  "driving_b",
  "driving_b1",

  "english",
  "polish",
  "russian",

  //   "arduino",
  //   "arduino", // TODO: this one course - from Spain
] as const;

export const tagTypes = [
  "company",
  "language",
  "framework",
  "technology",
  "tool",
  "operating_system",
  "cloud",
  "library",
  "database",
  "other",
  "linguistics",
] as const;

export type TagId = (typeof tagIds)[number];
export type TagType = (typeof tagTypes)[number];

export interface Tag {
  id: TagId;
  type: TagType;
  link?: string;
  translation: { en: string; pl?: string };
  level?: number;
}

export const tags: Record<TagId, Tag> = {
  sages: {
    id: "sages",
    type: "company",
    link: "https://www.sages.pl/",
    translation: { en: "Sages" },
  },
  side_project: {
    id: "side_project",
    type: "company",
    translation: { en: "Side Project", pl: "Poboczny Projekt" },
  },
  university: {
    id: "university",
    type: "company",
    link: "https://eng.pw.edu.pl/",
    translation: { en: "University", pl: "Uczelnia" },
  },
  thesis: {
    id: "thesis",
    type: "company",
    link: "https://eng.pw.edu.pl/",
    translation: { en: "Thesis", pl: "Praca Dyplomowa" },
  },
  cyfrowy_polsat: {
    id: "cyfrowy_polsat",
    type: "company",
    link: "https://www.polsatbox.pl/",
    translation: { en: "Polsat Box", pl: "Cyfrowy Polsat" },
  },
  it_run: {
    id: "it_run",
    type: "company",
    link: "https://itrun.com.pl/",
    translation: { en: "Polsat Box", pl: "Cyfrowy Polsat" },
  },
  java: {
    id: "java",
    type: "language",
    translation: { en: "Java" },
    link: "https://www.java.com/",
  },
  kotlin: {
    id: "kotlin",
    type: "language",
    link: "https://kotlinlang.org/",
    translation: { en: "Kotlin" },
  },
  groovy: {
    id: "groovy",
    type: "language",
    link: "https://groovy-lang.org/",
    translation: { en: "Groovy" },
  },
  scala: {
    id: "scala",
    type: "language",
    link: "https://www.scala-lang.org/",
    translation: { en: "Scala" },
  },
  c: {
    id: "c",
    type: "language",
    link: "https://www.c-language.org/",
    translation: { en: "C" },
  },
  cpp: {
    id: "cpp",
    type: "language",
    link: "https://en.cppreference.com/w/",
    translation: { en: "C++" },
  },
  sql: {
    id: "sql",
    type: "language",
    link: "https://pl.wikipedia.org/wiki/SQL",
    translation: { en: "SQL" },
  },
  python: {
    id: "python",
    type: "language",
    link: "https://www.python.org/",
    translation: { en: "Python" },
  },
  rust: {
    id: "rust",
    type: "language",
    link: "https://rust-lang.org/",
    translation: { en: "Rust" },
  },
  go: {
    id: "go",
    type: "language",
    link: "https://go.dev/",
    translation: { en: "Go Language" },
  },
  pl_sql: {
    id: "pl_sql",
    type: "language",
    link: "https://www.oracle.com/database/technologies/appdev/plsql.html",
    translation: { en: "PL/SQL" },
  },
  html: {
    id: "html",
    type: "language",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    translation: { en: "HTML" },
  },
  css: {
    id: "css",
    type: "language",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    translation: { en: "CSS" },
  },
  javascript: {
    id: "javascript",
    type: "language",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    translation: { en: "JavaScript" },
  },
  typescript: {
    id: "typescript",
    type: "language",
    link: "https://www.typescriptlang.org/",
    translation: { en: "TypeScript" },
  },
  haskell: {
    id: "haskell",
    type: "language",
    link: "https://www.haskell.org/",
    translation: { en: "Haskell" },
  },
  prolog: {
    id: "prolog",
    type: "language",
    link: "https://www.swi-prolog.org/",
    translation: { en: "Prolog" },
  },
  bash: {
    id: "bash",
    type: "language",
    link: "https://www.gnu.org/software/bash/",
    translation: { en: "Bash" },
  },
  ampl: {
    id: "ampl",
    type: "language",
    link: "https://ampl.com/",
    translation: { en: "AMPL" },
  },
  tex: {
    id: "tex",
    type: "language",
    link: "https://www.latex-project.org/get/",
    translation: { en: "LaTeX" },
  },
  matlab: {
    id: "matlab",
    type: "language",
    link: "https://www.mathworks.com/products/matlab.html",
    translation: { en: "Matlab" },
  },
  assembly_x86: {
    id: "assembly_x86",
    type: "language",
    link: "https://en.wikipedia.org/wiki/X86_assembly_language",
    translation: { en: "x86 assembly" },
  },
  assembly_mips: {
    id: "assembly_mips",
    type: "language",
    link: "https://en.wikibooks.org/wiki/MIPS_Assembly/MIPS_Instructions",
    translation: { en: "MIPS assembly" },
  },
  spring: {
    id: "spring",
    type: "framework",
    link: "https://spring.io/projects/spring-framework",
    translation: { en: "Spring" },
  },
  ktor: {
    id: "ktor",
    type: "framework",
    link: "https://ktor.io/",
    translation: { en: "Ktor" },
  },
  helidon: {
    id: "helidon",
    type: "framework",
    link: "https://helidon.io/",
    translation: { en: "Helidon" },
  },
  micronaut: {
    id: "micronaut",
    type: "framework",
    link: "https://micronaut.io/",
    translation: { en: "Micronaut" },
  },
  jsf: {
    id: "jsf",
    type: "framework",
    link: "https://github.com/jakartaee/faces",
    translation: { en: "Java Server Faces" },
  },
  prime_faces: {
    id: "prime_faces",
    type: "framework",
    link: "https://www.primefaces.org/",
    translation: { en: "Prime Faces" },
  },
  hibernate: {
    id: "hibernate",
    type: "framework",
    link: "https://hibernate.org/",
    translation: { en: "Hibernate" },
  },
  jakarta_ee: {
    id: "jakarta_ee",
    type: "framework",
    link: "https://jakarta.ee/specifications/",
    translation: { en: "Jakarta CDI" },
  },
  jax_rs: {
    id: "jax_rs",
    type: "framework",
    link: "https://projects.eclipse.org/projects/ee4j.rest",
    translation: { en: "Jakarta RESTful Web Services" },
  },
  jakarta_cdi: {
    id: "jakarta_cdi",
    type: "framework",
    link: "https://www.cdi-spec.org/",
    translation: { en: "Jakarta CDI" },
  },
  jboss_seam: {
    id: "jboss_seam",
    type: "framework",
    link: "https://www.seamframework.org/",
    translation: { en: "JBoss Seam" },
  },
  apache_hadoop: {
    id: "apache_hadoop",
    type: "framework",
    link: "https://hadoop.apache.org/",
    translation: { en: "Apache Hadoop" },
  },
  axon: {
    id: "axon",
    type: "framework",
    link: "https://www.axoniq.io/framework",
    translation: { en: "AXON Framework" },
  },
  android: {
    id: "android",
    type: "framework",
    link: "https://developer.android.com/",
    translation: { en: "Android" },
  },
  react_js: {
    id: "react_js",
    type: "framework",
    link: "https://react.dev/",
    translation: { en: "React.js" },
  },
  astro_js: {
    id: "astro_js",
    type: "framework",
    link: "https://astro.build/",
    translation: { en: "Astro.js" },
  },
  django: {
    id: "django",
    type: "framework",
    link: "https://www.djangoproject.com/",
    translation: { en: "Django" },
  },
  flask: {
    id: "flask",
    type: "framework",
    link: "https://flask.palletsprojects.com/en/stable/",
    translation: { en: "Flask" },
  },
  docker: {
    id: "docker",
    type: "technology",
    link: "https://www.docker.com/",
    translation: { en: "Docker" },
  },
  kubernetes: {
    id: "kubernetes",
    type: "technology",
    link: "https://kubernetes.io/",
    translation: { en: "Kubernetes" },
  },
  ci_cd: {
    id: "ci_cd",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/CI/CD",
    translation: { en: "CI/CD" },
  },
  s3: {
    id: "s3",
    type: "technology",
    link: "https://aws.amazon.com/s3/",
    translation: { en: "Amazon S3" },
  },
  iac: {
    id: "iac",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Infrastructure_as_code",
    translation: { en: "Infrastructure as Code" },
  },
  ddd: {
    id: "ddd",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Domain-driven_design",
    translation: { en: "Domain Driven Design" },
  },
  agile: {
    id: "agile",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Agile_software_development",
    translation: { en: "Agile" },
  },
  scrum: {
    id: "scrum",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Scrum_(project_management)",
    translation: { en: "Scrum" },
  },
  kanban: {
    id: "kanban",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Kanban",
    translation: { en: "Kanban" },
  },
  rest_api: {
    id: "rest_api",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/REST",
    translation: { en: "REST API" },
  },
  grpc: {
    id: "grpc",
    type: "technology",
    link: "https://grpc.io/",
    translation: { en: "gRPC" },
  },
  cqrs: {
    id: "cqrs",
    type: "technology",
    link: "https://martinfowler.com/bliki/CQRS.html",
    translation: { en: "CQRS" },
  },
  event_sourcing: {
    id: "event_sourcing",
    type: "technology",
    link: "https://microservices.io/patterns/data/event-sourcing.html",
    translation: { en: "Event Sourcing" },
  },
  dsl: {
    id: "dsl",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Domain-specific_language",
    translation: { en: "Domain Specific Language" },
  },
  replication: {
    id: "replication",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Replication_(computing)",
    translation: { en: "Replication" },
  },
  load_balancing: {
    id: "load_balancing",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Load_balancing_(computing)",
    translation: { en: "Load Balancing", pl: "Równoważenie obciążenia" },
  },
  circuit_breaker: {
    id: "circuit_breaker",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern",
    translation: { en: "Circuit Breaker" },
  },
  service_discovery: {
    id: "service_discovery",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Service_discovery",
    translation: { en: "Service Discovery" },
  },
  service_registry: {
    id: "service_registry",
    type: "technology",
    link: "https://microservices.io/patterns/service-registry.html",
    translation: { en: "Service Registry" },
  },
  basic_auth: {
    id: "basic_auth",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Basic_access_authentication",
    translation: { en: "Basic Auth" },
  },
  oauth2: {
    id: "oauth2",
    type: "technology",
    link: "https://oauth.net/2/",
    translation: { en: "OAuth 2.0" },
  },
  rbac: {
    id: "rbac",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Role-based_access_control",
    translation: { en: "Role Based Access Control" },
  },
  otp: {
    id: "otp",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/One-time_password",
    translation: { en: "One-Time Password" },
  },
  ansible: {
    id: "ansible",
    type: "tool",
    link: "https://docs.ansible.com/",
    translation: { en: "Ansible" },
  },
  puppet: {
    id: "puppet",
    type: "tool",
    link: "https://www.puppet.com/",
    translation: { en: "Puppet" },
  },
  gradle: {
    id: "gradle",
    type: "tool",
    link: "https://gradle.org/",
    translation: { en: "Gradle" },
  },
  maven: {
    id: "maven",
    type: "tool",
    link: "https://maven.apache.org/",
    translation: { en: "Maven" },
  },
  sbt: {
    id: "sbt",
    type: "tool",
    link: "https://www.scala-sbt.org/",
    translation: { en: "SBT" },
  },
  node_js: {
    id: "node_js",
    type: "tool",
    link: "https://nodejs.org/",
    translation: { en: "Node.js" },
  },
  git: {
    id: "git",
    type: "tool",
    link: "https://git-scm.com/",
    translation: { en: "git" },
  },
  github: {
    id: "github",
    type: "tool",
    link: "https://github.com/",
    translation: { en: "Github" },
  },
  gitlab: {
    id: "gitlab",
    type: "tool",
    link: "https://about.gitlab.com/",
    translation: { en: "GitLab" },
  },
  bitbucket: {
    id: "bitbucket",
    type: "tool",
    link: "https://bitbucket.org/product/",
    translation: { en: "Bitbucket" },
  },
  jira: {
    id: "jira",
    type: "tool",
    link: "https://www.atlassian.com/software/jira",
    translation: { en: "Jira" },
  },
  trello: {
    id: "trello",
    type: "tool",
    link: "https://trello.com/",
    translation: { en: "Trello" },
  },
  makefile: {
    id: "makefile",
    type: "tool",
    link: "https://www.gnu.org/software/make/manual/make.html",
    translation: { en: "Makefile" },
  },
  jenkins: {
    id: "jenkins",
    type: "tool",
    link: "https://www.jenkins.io/",
    translation: { en: "Jenkins" },
  },
  github_actions: {
    id: "github_actions",
    type: "tool",
    link: "https://github.com/features/actions",
    translation: { en: "Github Actions" },
  },
  bitbucket_pipelines: {
    id: "bitbucket_pipelines",
    type: "tool",
    link: "https://www.atlassian.com/software/bitbucket/features/pipelines",
    translation: { en: "Bitbucket Pipelines" },
  },
  gitlab_ci: {
    id: "gitlab_ci",
    type: "tool",
    link: "https://docs.gitlab.com/ci/",
    translation: { en: "GitLab CI/CD" },
  },
  nginx: {
    id: "nginx",
    type: "tool",
    link: "https://nginx.org/",
    translation: { en: "NGINX" },
  },
  apache: {
    id: "apache",
    type: "tool",
    link: "https://httpd.apache.org/",
    translation: { en: "Apache" },
  },
  certbot: {
    id: "certbot",
    type: "tool",
    link: "https://certbot.eff.org/",
    translation: { en: "Certbot" },
  },
  ssh: {
    id: "ssh",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Secure_Shell",
    translation: { en: "SSH" },
  },
  vscode: {
    id: "vscode",
    type: "tool",
    link: "https://code.visualstudio.com/",
    translation: { en: "VS Code" },
  },
  intellij: {
    id: "intellij",
    type: "tool",
    link: "https://www.jetbrains.com/idea/",
    translation: { en: "IntelliJ IDEA" },
  },
  pycharm: {
    id: "pycharm",
    type: "tool",
    link: "https://www.jetbrains.com/pycharm/",
    translation: { en: "PyCharm" },
  },
  go_land: {
    id: "go_land",
    type: "tool",
    link: "https://www.jetbrains.com/go/",
    translation: { en: "GoLand" },
  },
  rust_rover: {
    id: "rust_rover",
    type: "tool",
    link: "https://www.jetbrains.com/rust/",
    translation: { en: "RustRover" },
  },
  c_lion: {
    id: "c_lion",
    type: "tool",
    link: "https://www.jetbrains.com/clion/",
    translation: { en: "CLion" },
  },
  data_grip: {
    id: "data_grip",
    type: "tool",
    link: "https://www.jetbrains.com/datagrip/",
    translation: { en: "DataGrip" },
  },
  ms_office: {
    id: "ms_office",
    type: "tool",
    link: "https://www.microsoft.com/microsoft-365",
    translation: { en: "MS Office" },
  },
  libre_office: {
    id: "libre_office",
    type: "tool",
    link: "https://www.libreoffice.org/",
    translation: { en: "Libre Office" },
  },
  google_workspace: {
    id: "google_workspace",
    type: "tool",
    link: "https://workspace.google.com/",
    translation: { en: "Google Workspace" },
  },
  chat_gpt: {
    id: "chat_gpt",
    type: "tool",
    link: "https://chatgpt.com/",
    translation: { en: "ChatGPT" },
  },
  gemini: {
    id: "gemini",
    type: "tool",
    link: "https://gemini.google.com/app",
    translation: { en: "Gemini" },
  },
  copilot: {
    id: "copilot",
    type: "tool",
    link: "https://copilot.microsoft.com/",
    translation: { en: "Copilot" },
  },
  rovo_dev: {
    id: "rovo_dev",
    type: "tool",
    link: "https://www.atlassian.com/software/rovo-dev",
    translation: { en: "Rovo Dev" },
  },
  keycloak: {
    id: "keycloak",
    type: "tool",
    link: "https://www.keycloak.org/",
    translation: { en: "Keycloak" },
  },
  liquibase: {
    id: "liquibase",
    type: "tool",
    link: "https://www.liquibase.com/",
    translation: { en: "Liquibase" },
  },
  sonar_qube: {
    id: "sonar_qube",
    type: "tool",
    link: "https://www.sonarsource.com/products/sonarqube/",
    translation: { en: "SonarQube" },
  },
  open_api: {
    id: "open_api",
    type: "tool",
    link: "https://www.openapis.org/",
    translation: { en: "Open API" },
  },
  swagger: {
    id: "swagger",
    type: "tool",
    link: "https://swagger.io/",
    translation: { en: "Swagger" },
  },
  linux: {
    id: "linux",
    type: "operating_system",
    translation: { en: "Linux" },
  },
  ubuntu: {
    id: "ubuntu",
    type: "operating_system",
    link: "https://ubuntu.com/",
    translation: { en: "Ubuntu" },
  },
  windows: {
    id: "windows",
    type: "operating_system",
    link: "https://www.microsoft.com/windows",
    translation: { en: "Windows" },
  },
  wsl: {
    id: "wsl",
    type: "operating_system",
    link: "https://learn.microsoft.com/en-us/windows/wsl/install",
    translation: { en: "WSL" },
  },
  azure: {
    id: "azure",
    type: "cloud",
    link: "https://azure.microsoft.com/",
    translation: { en: "Azure" },
  },
  gcp: {
    id: "gcp",
    type: "cloud",
    link: "https://cloud.google.com/",
    translation: { en: "Google Cloud" },
  },
  oci: {
    id: "oci",
    type: "cloud",
    link: "https://www.oracle.com/cloud/",
    translation: { en: "Oracle Cloud Infrastructure" },
  },
  ovh: {
    id: "ovh",
    type: "cloud",
    link: "https://www.ovhcloud.com/pl/",
    translation: { en: "OVH Cloud" },
  },
  pandas: {
    id: "pandas",
    type: "library",
    link: "https://pandas.pydata.org/",
    translation: { en: "Pandas" },
  },
  apache_hive: {
    id: "apache_hive",
    type: "database",
    link: "https://hive.apache.org/",
    translation: { en: "Apache Hive" },
  },
  mongo_db: {
    id: "mongo_db",
    type: "database",
    link: "https://www.mongodb.com/",
    translation: { en: "MongoDB" },
  },
  arango_db: {
    id: "arango_db",
    type: "database",
    link: "https://www.arangodb.com",
    translation: { en: "ArangoDB" },
  },
  postgres: {
    id: "postgres",
    type: "database",
    link: "https://www.postgresql.org",
    translation: { en: "PostgreSQL" },
  },
  oracle: {
    id: "oracle",
    type: "database",
    link: "https://www.oracle.com/database/technologies/",
    translation: { en: "Oracle Database" },
  },
  mysql: {
    id: "mysql",
    type: "database",
    link: "https://www.mysql.com/",
    translation: { en: "MySQL" },
  },
  mariadb: {
    id: "mariadb",
    type: "database",
    link: "https://mariadb.org/",
    translation: { en: "MariaDB" },
  },
  sqlite: {
    id: "sqlite",
    type: "database",
    link: "https://sqlite.org/",
    translation: { en: "SQLite" },
  },
  redis: {
    id: "redis",
    type: "database",
    link: "https://redis.io/",
    translation: { en: "Redis" },
  },
  ms_access: {
    id: "ms_access",
    type: "database",
    link: "https://www.microsoft.com/microsoft-365/access",
    translation: { en: "Microsoft Access" },
  },
  firebase: {
    id: "firebase",
    type: "database",
    link: "https://firebase.google.com/",
    translation: { en: "Firebase" },
  },
  h2: {
    id: "h2",
    type: "database",
    link: "https://www.h2database.com/html/main.html",
    translation: { en: "H2 Database" },
  },
  driving: {
    id: "driving",
    type: "other",
    link: "https://www.gov.pl/web/gov/kategorie-prawa-jazdy",
    translation: { en: "Driving License", pl: "Prawo Jazdy" },
  },
  driving_am: {
    id: "driving_am",
    type: "other",
    link: "https://www.gov.pl/web/gov/kategorie-prawa-jazdy",
    translation: { en: "Driving License - AM", pl: "Prawo Jazdy - AM" },
  },
  driving_b: {
    id: "driving_b",
    type: "other",
    link: "https://www.gov.pl/web/gov/kategorie-prawa-jazdy",
    translation: { en: "Driving License - B", pl: "Prawo Jazdy - B" },
  },
  driving_b1: {
    id: "driving_b1",
    type: "other",
    link: "https://www.gov.pl/web/gov/kategorie-prawa-jazdy",
    translation: { en: "Driving License - B1", pl: "Prawo Jazdy - B1" },
  },
  polish: {
    id: "polish",
    type: "linguistics",
    link: "https://en.wikipedia.org/wiki/Polish_language",
    translation: { en: "Polish - native", pl: "Polski - ojczysty" },
  },
  english: {
    id: "english",
    type: "linguistics",
    link: "https://en.wikipedia.org/wiki/English_language",
    translation: { en: "English - advanced", pl: "Angielski - zaawansowany" },
  },
  russian: {
    id: "russian",
    type: "linguistics",
    link: "https://en.wikipedia.org/wiki/English_language",
    translation: { en: "Russian - basic", pl: "Rosyjski - podstawowy" },
  },
};
