export const tagIds = [
  "sages",
  "side_project",
  "university",
  "thesis",
  "cyfrowy_polsat",
  "it_run",

  "java",
  "kotlin",
  "sql",
  "scala",
  "python",
  "rust",
  "go",
  "c",
  "cpp",
  "pl_sql",
  "html",
  "css",
  "javascript",
  "typescript",
  "haskell",
  "prolog",
  "bash",
  "groovy",
  "ampl",
  "tex",
  "matlab",
  "assembly_x86",
  "assembly_mips",
  "makefile",

  "spring",
  "ktor",
  "helidon",
  "micronaut",
  "jsf",
  "prime_faces",
  "hibernate",
  "jakarta_ee",
  "apache_hadoop",
  "axon",
  "android",
  "react_js",
  "astro_js",
  "django",
  "flask",

  "functional_programming",
  "linear_programming",
  "mip",

  "docker",
  "kubernetes",
  "ci_cd",
  "s3",
  "iac",

  "ddd",
  "wcag",

  "rest_api",
  "graph_ql",
  "grpc",
  "cqrs",
  "event_sourcing",
  "dsl",

  "microservices",
  "distributed_systems",
  "observability",
  "replication",
  "load_balancing",
  "circuit_breaker",
  "service_discovery",
  "service_registry",

  "oauth2",
  "rbac",
  "otp",

  "ai",

  "ansible",
  "puppet",

  "git",

  "jenkins",
  "github_actions",
  "bitbucket_pipelines",
  "gitlab_ci",
  "nginx",
  "apache",
  "ssh",

  "apache_rabbit_mq",
  "apache_kafka",
  "apache_flink",
  "apache_spark",
  "apache_solr",
  "elastic_search",
  "cas",
  "hazelcast",
  "prometheus",
  "grafana",
  "kibana",
  "filebeat",
  "logstash",

  "keycloak",
  "liquibase",
  "3d_printing",

  "open_api",
  "swagger",

  "linux",
  "windows",
  "ubuntu",
  "wsl",
  "kvm",
  // "virtual_box",
  // "vmware",

  "azure",
  "gcp",
  "oci",
  "ovh",

  "deep_java_library",
  "open_cv",
  "jetbrains_exposed",
  "or_tools",

  "tailwind",
  "expressive_code",
  "playwright",
  "rehype",
  "remark",

  "pandas",
  "py_spark",
  "py_torch",
  "scikit_learn",
  "keras",
  "num_py",
  "matplotlib",

  "testing",

  "spring_boot",
  "spring_data",
  "spring_security",
  "spring_cloud",
  "spring_mvc",
  "spring_webflux",

  "androidx",
  "android_material",
  "play_services_vision",
  "room",
  "lombok",
  "retrofit",
  "rocket",
  "burn",
  "rayon",

  "mongo_db",
  "arango_db",
  "postgres",
  "oracle",
  "mysql",
  "mariadb",
  "sqlite",
  "redis",
  "firebase",

  "driving",
  "driving_b",

  "english",
  "polish",
  "russian",

  "arduino",
  "raspberry_pi",
] as const;

export const tagTypes = [
  "company",
  "language",
  "niche_language",
  "framework",
  "technology",
  "tool",
  "operating_system",
  "cloud",
  "library",
  "database",
  "other",
  "linguistics",
] as const;

export type TagId = (typeof tagIds)[number];
export type TagType = (typeof tagTypes)[number];

export interface Tag {
  id: TagId;
  type: TagType;
  link?: string;
  translation: { en: string; pl?: string };
  level?: number;
  print?: boolean;
}

export const tags: Record<TagId, Tag> = {
  sages: {
    id: "sages",
    type: "company",
    link: "https://www.sages.pl/",
    translation: { en: "Sages" },
  },
  side_project: {
    id: "side_project",
    type: "company",
    translation: { en: "Side Project", pl: "Poboczny Projekt" },
  },
  university: {
    id: "university",
    type: "company",
    link: "https://eng.pw.edu.pl/",
    translation: { en: "University", pl: "Uczelnia" },
  },
  thesis: {
    id: "thesis",
    type: "company",
    link: "https://eng.pw.edu.pl/",
    translation: { en: "Thesis", pl: "Praca Dyplomowa" },
  },
  cyfrowy_polsat: {
    id: "cyfrowy_polsat",
    type: "company",
    link: "https://www.polsatbox.pl/",
    translation: { en: "Polsat Box", pl: "Cyfrowy Polsat" },
  },
  it_run: {
    id: "it_run",
    type: "company",
    link: "https://itrun.com.pl/",
    translation: { en: "Polsat Box", pl: "Cyfrowy Polsat" },
  },
  java: {
    id: "java",
    type: "language",
    translation: { en: "Java" },
    link: "https://www.java.com/",
    print: true,
  },
  kotlin: {
    id: "kotlin",
    type: "language",
    link: "https://kotlinlang.org/",
    translation: { en: "Kotlin" },
    print: true,
  },
  groovy: {
    id: "groovy",
    type: "language",
    link: "https://groovy-lang.org/",
    translation: { en: "Groovy" },
  },
  scala: {
    id: "scala",
    type: "language",
    link: "https://www.scala-lang.org/",
    translation: { en: "Scala" },
  },
  c: {
    id: "c",
    type: "language",
    link: "https://www.c-language.org/",
    translation: { en: "C" },
  },
  cpp: {
    id: "cpp",
    type: "language",
    link: "https://en.cppreference.com/w/",
    translation: { en: "C++" },
  },
  sql: {
    id: "sql",
    type: "language",
    link: "https://pl.wikipedia.org/wiki/SQL",
    translation: { en: "SQL" },
    print: true,
  },
  python: {
    id: "python",
    type: "language",
    link: "https://www.python.org/",
    translation: { en: "Python" },
    print: true,
  },
  rust: {
    id: "rust",
    type: "language",
    link: "https://rust-lang.org/",
    translation: { en: "Rust" },
    print: true,
  },
  go: {
    id: "go",
    type: "language",
    link: "https://go.dev/",
    translation: { en: "Go Language" },
  },
  pl_sql: {
    id: "pl_sql",
    type: "language",
    link: "https://www.oracle.com/database/technologies/appdev/plsql.html",
    translation: { en: "PL/SQL" },
  },
  html: {
    id: "html",
    type: "language",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    translation: { en: "HTML" },
  },
  css: {
    id: "css",
    type: "language",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    translation: { en: "CSS" },
  },
  javascript: {
    id: "javascript",
    type: "language",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    translation: { en: "JavaScript" },
  },
  typescript: {
    id: "typescript",
    type: "language",
    link: "https://www.typescriptlang.org/",
    translation: { en: "TypeScript" },
    print: true,
  },
  haskell: {
    id: "haskell",
    type: "language",
    link: "https://www.haskell.org/",
    translation: { en: "Haskell" },
  },
  prolog: {
    id: "prolog",
    type: "niche_language",
    link: "https://www.swi-prolog.org/",
    translation: { en: "Prolog" },
  },
  bash: {
    id: "bash",
    type: "language",
    link: "https://www.gnu.org/software/bash/",
    translation: { en: "Bash" },
    print: true,
  },
  ampl: {
    id: "ampl",
    type: "niche_language",
    link: "https://ampl.com/",
    translation: { en: "AMPL" },
  },
  tex: {
    id: "tex",
    type: "language",
    link: "https://www.latex-project.org/get/",
    translation: { en: "LaTeX" },
  },
  matlab: {
    id: "matlab",
    type: "language",
    link: "https://www.mathworks.com/products/matlab.html",
    translation: { en: "Matlab" },
  },
  assembly_x86: {
    id: "assembly_x86",
    type: "niche_language",
    link: "https://en.wikipedia.org/wiki/X86_assembly_language",
    translation: { en: "x86 assembly" },
  },
  assembly_mips: {
    id: "assembly_mips",
    type: "niche_language",
    link: "https://en.wikibooks.org/wiki/MIPS_Assembly/MIPS_Instructions",
    translation: { en: "MIPS assembly" },
  },
  spring: {
    id: "spring",
    type: "framework",
    link: "https://spring.io/projects/spring-framework",
    translation: { en: "Spring" },
    print: true,
  },
  ktor: {
    id: "ktor",
    type: "framework",
    link: "https://ktor.io/",
    translation: { en: "Ktor" },
    print: true,
  },
  helidon: {
    id: "helidon",
    type: "framework",
    link: "https://helidon.io/",
    translation: { en: "Helidon" },
    print: true,
  },
  micronaut: {
    id: "micronaut",
    type: "framework",
    link: "https://micronaut.io/",
    translation: { en: "Micronaut" },
    print: true,
  },
  jsf: {
    id: "jsf",
    type: "framework",
    link: "https://github.com/jakartaee/faces",
    translation: { en: "Java Server Faces" },
  },
  prime_faces: {
    id: "prime_faces",
    type: "framework",
    link: "https://www.primefaces.org/",
    translation: { en: "Prime Faces" },
  },
  hibernate: {
    id: "hibernate",
    type: "framework",
    link: "https://hibernate.org/",
    translation: { en: "Hibernate" },
  },
  jakarta_ee: {
    id: "jakarta_ee",
    type: "framework",
    link: "https://jakarta.ee/specifications/",
    translation: { en: "Jakarta EE" },
  },
  rocket: {
    id: "rocket",
    type: "framework",
    link: "https://rocket.rs/",
    translation: { en: "Rocket.rs" },
    print: true,
  },
  apache_hadoop: {
    id: "apache_hadoop",
    type: "framework",
    link: "https://hadoop.apache.org/",
    translation: { en: "Apache Hadoop" },
  },
  axon: {
    id: "axon",
    type: "framework",
    link: "https://www.axoniq.io/framework",
    translation: { en: "AXON Framework" },
    print: true,
  },
  android: {
    id: "android",
    type: "framework",
    link: "https://developer.android.com/",
    translation: { en: "Android" },
    print: true,
  },
  react_js: {
    id: "react_js",
    type: "framework",
    link: "https://react.dev/",
    translation: { en: "React.js" },
  },
  astro_js: {
    id: "astro_js",
    type: "framework",
    link: "https://astro.build/",
    translation: { en: "Astro.js" },
    print: true,
  },
  django: {
    id: "django",
    type: "framework",
    link: "https://www.djangoproject.com/",
    translation: { en: "Django" },
  },
  flask: {
    id: "flask",
    type: "framework",
    link: "https://flask.palletsprojects.com/en/stable/",
    translation: { en: "Flask" },
  },
  linear_programming: {
    id: "linear_programming",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Linear_programming",
    translation: { en: "Linear Programming", pl: "Programowanie Liniowe" },
    print: true,
  },
  functional_programming: {
    id: "functional_programming",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Functional_programming",
    translation: {
      en: "Functional Programming",
      pl: "Programowanie Funkcyjne",
    },
    print: true,
  },
  mip: {
    id: "mip",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Integer_programming",
    translation: {
      en: "Mixed Integer Programming",
      pl: "Programowanie Mieszane Całkowitoliczbowe",
    },
    print: true,
  },
  microservices: {
    id: "microservices",
    type: "technology",
    link: "https://microservices.io/",
    translation: { en: "Microservices", pl: "Mikroserwisy" },
    print: true,
  },
  distributed_systems: {
    id: "distributed_systems",
    type: "technology",
    link: "https://martinfowler.com/articles/patterns-of-distributed-systems/",
    translation: { en: "Distributed Systems", pl: "Systemy Rozproszone" },
    print: true,
  },
  observability: {
    id: "observability",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Observability_(software)",
    translation: { en: "Observability", pl: "Obserwowalność" },
    print: true,
  },
  docker: {
    id: "docker",
    type: "technology",
    link: "https://www.docker.com/",
    translation: { en: "Docker" },
    print: true,
  },
  kubernetes: {
    id: "kubernetes",
    type: "technology",
    link: "https://kubernetes.io/",
    translation: { en: "Kubernetes" },
    print: true,
  },
  ci_cd: {
    id: "ci_cd",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/CI/CD",
    translation: { en: "CI/CD" },
    print: true,
  },
  testing: {
    id: "testing",
    type: "technology",
    translation: { en: "Testing", pl: "Testowanie" },
    print: true,
  },
  // TODO: s3 to aws?
  s3: {
    id: "s3",
    type: "technology",
    link: "https://aws.amazon.com/s3/",
    translation: { en: "Amazon S3" },
    print: true,
  },
  iac: {
    id: "iac",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Infrastructure_as_code",
    translation: { en: "Infrastructure as Code" },
    print: true,
  },
  ddd: {
    id: "ddd",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Domain-driven_design",
    translation: { en: "Domain Driven Design" },
  },
  rest_api: {
    id: "rest_api",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/REST",
    translation: { en: "REST API" },
  },
  grpc: {
    id: "grpc",
    type: "technology",
    link: "https://grpc.io/",
    translation: { en: "gRPC" },
  },
  // distributed_systems?
  cqrs: {
    id: "cqrs",
    type: "technology",
    link: "https://martinfowler.com/bliki/CQRS.html",
    translation: { en: "CQRS" },
    print: true,
  },
  event_sourcing: {
    id: "event_sourcing",
    type: "technology",
    link: "https://microservices.io/patterns/data/event-sourcing.html",
    translation: { en: "Event Sourcing" },
    print: true,
  },
  dsl: {
    id: "dsl",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Domain-specific_language",
    translation: { en: "Domain Specific Language" },
  },
  replication: {
    id: "replication",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Replication_(computing)",
    translation: { en: "Replication" },
  },
  load_balancing: {
    id: "load_balancing",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Load_balancing_(computing)",
    translation: { en: "Load Balancing", pl: "Równoważenie obciążenia" },
  },
  circuit_breaker: {
    id: "circuit_breaker",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Circuit_breaker_design_pattern",
    translation: { en: "Circuit Breaker" },
  },
  service_discovery: {
    id: "service_discovery",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Service_discovery",
    translation: { en: "Service Discovery" },
  },
  service_registry: {
    id: "service_registry",
    type: "technology",
    link: "https://microservices.io/patterns/service-registry.html",
    translation: { en: "Service Registry" },
  },
  oauth2: {
    id: "oauth2",
    type: "technology",
    link: "https://oauth.net/2/",
    translation: { en: "OAuth 2.0" },
  },
  rbac: {
    id: "rbac",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Role-based_access_control",
    translation: { en: "Role Based Access Control" },
  },
  otp: {
    id: "otp",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/One-time_password",
    translation: { en: "One-Time Password" },
  },
  wcag: {
    id: "wcag",
    type: "technology",
    link: "https://www.w3.org/WAI/standards-guidelines/wcag/",
    translation: { en: "WCAG" },
  },
  graph_ql: {
    id: "graph_ql",
    type: "technology",
    link: "https://graphql.org/",
    translation: { en: "GraphQL" },
  },
  ai: {
    id: "ai",
    type: "technology",
    link: "https://en.wikipedia.org/wiki/Artificial_intelligence",
    translation: { en: "Artificial Intelligence", pl: "Sztuczna Inteligencja" },
  },
  ansible: {
    id: "ansible",
    type: "tool",
    link: "https://docs.ansible.com/",
    translation: { en: "Ansible" },
  },
  puppet: {
    id: "puppet",
    type: "tool",
    link: "https://www.puppet.com/",
    translation: { en: "Puppet" },
  },
  git: {
    id: "git",
    type: "tool",
    link: "https://git-scm.com/",
    translation: { en: "git" },
  },
  makefile: {
    id: "makefile",
    type: "tool",
    link: "https://www.gnu.org/software/make/manual/make.html",
    translation: { en: "Makefile" },
  },
  jenkins: {
    id: "jenkins",
    type: "tool",
    link: "https://www.jenkins.io/",
    translation: { en: "Jenkins" },
  },
  github_actions: {
    id: "github_actions",
    type: "tool",
    link: "https://github.com/features/actions",
    translation: { en: "Github Actions" },
  },
  bitbucket_pipelines: {
    id: "bitbucket_pipelines",
    type: "tool",
    link: "https://www.atlassian.com/software/bitbucket/features/pipelines",
    translation: { en: "Bitbucket Pipelines" },
  },
  gitlab_ci: {
    id: "gitlab_ci",
    type: "tool",
    link: "https://docs.gitlab.com/ci/",
    translation: { en: "GitLab CI/CD" },
  },
  nginx: {
    id: "nginx",
    type: "tool",
    link: "https://nginx.org/",
    translation: { en: "NGINX" },
  },
  apache: {
    id: "apache",
    type: "tool",
    link: "https://httpd.apache.org/",
    translation: { en: "Apache" },
  },
  ssh: {
    id: "ssh",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/Secure_Shell",
    translation: { en: "SSH" },
  },
  apache_rabbit_mq: {
    id: "apache_rabbit_mq",
    type: "tool",
    link: "https://www.rabbitmq.com/",
    translation: { en: "RabbitMQ" },
  },
  apache_kafka: {
    id: "apache_kafka",
    type: "tool",
    link: "https://kafka.apache.org/",
    translation: { en: "Apache Kafka" },
  },
  apache_solr: {
    id: "apache_solr",
    type: "tool",
    link: "https://solr.apache.org/",
    translation: { en: "Apache Solr" },
  },
  apache_spark: {
    id: "apache_spark",
    type: "tool",
    link: "https://spark.apache.org/",
    translation: { en: "Apache Spark" },
  },
  apache_flink: {
    id: "apache_flink",
    type: "tool",
    link: "https://flink.apache.org/",
    translation: { en: "Apache Flink" },
  },
  elastic_search: {
    id: "elastic_search",
    type: "tool",
    link: "https://www.elastic.co/elasticsearch/",
    translation: { en: "Elasticsearch" },
  },
  cas: {
    id: "cas",
    type: "tool",
    link: "https://www.apereo.org/projects/cas",
    translation: { en: "CAS" },
  },
  hazelcast: {
    id: "hazelcast",
    type: "tool",
    link: "https://hazelcast.com/",
    translation: { en: "Hazelcast" },
  },
  prometheus: {
    id: "prometheus",
    type: "tool",
    link: "https://prometheus.io/",
    translation: { en: "Prometheus" },
  },
  grafana: {
    id: "grafana",
    type: "tool",
    link: "https://grafana.com/",
    translation: { en: "Grafana" },
  },
  kibana: {
    id: "kibana",
    type: "tool",
    link: "https://www.elastic.co/kibana",
    translation: { en: "Kibana" },
  },
  filebeat: {
    id: "filebeat",
    type: "tool",
    link: "https://www.elastic.co/beats/filebeat",
    translation: { en: "Filebeat" },
  },
  logstash: {
    id: "logstash",
    type: "tool",
    link: "https://www.elastic.co/logstash",
    translation: { en: "Logstash" },
  },
  keycloak: {
    id: "keycloak",
    type: "tool",
    link: "https://www.keycloak.org/",
    translation: { en: "Keycloak" },
  },
  liquibase: {
    id: "liquibase",
    type: "tool",
    link: "https://www.liquibase.com/",
    translation: { en: "Liquibase" },
  },
  "3d_printing": {
    id: "3d_printing",
    type: "tool",
    link: "https://en.wikipedia.org/wiki/3D_printing",
    translation: { en: "3D printing" },
  },
  open_api: {
    id: "open_api",
    type: "tool",
    link: "https://www.openapis.org/",
    translation: { en: "Open API" },
  },
  swagger: {
    id: "swagger",
    type: "tool",
    link: "https://swagger.io/",
    translation: { en: "Swagger" },
  },
  kvm: {
    id: "kvm",
    type: "tool",
    link: "https://linux-kvm.org/page/Main_Page",
    translation: { en: "Kernel-based Virtual Machine" },
  },
  linux: {
    id: "linux",
    type: "operating_system",
    translation: { en: "Linux" },
  },
  ubuntu: {
    id: "ubuntu",
    type: "operating_system",
    link: "https://ubuntu.com/",
    translation: { en: "Ubuntu" },
  },
  windows: {
    id: "windows",
    type: "operating_system",
    link: "https://www.microsoft.com/windows",
    translation: { en: "Windows" },
  },
  wsl: {
    id: "wsl",
    type: "operating_system",
    link: "https://learn.microsoft.com/en-us/windows/wsl/install",
    translation: { en: "WSL" },
  },
  azure: {
    id: "azure",
    type: "cloud",
    link: "https://azure.microsoft.com/",
    translation: { en: "Azure" },
  },
  gcp: {
    id: "gcp",
    type: "cloud",
    link: "https://cloud.google.com/",
    translation: { en: "Google Cloud" },
  },
  oci: {
    id: "oci",
    type: "cloud",
    link: "https://www.oracle.com/cloud/",
    translation: { en: "Oracle Cloud Infrastructure" },
  },
  ovh: {
    id: "ovh",
    type: "cloud",
    link: "https://www.ovhcloud.com/pl/",
    translation: { en: "OVH Cloud" },
  },
  spring_boot: {
    id: "spring_boot",
    type: "library",
    link: "https://spring.io/projects/spring-boot",
    translation: { en: "Spring Boot" },
  },
  spring_data: {
    id: "spring_data",
    type: "library",
    link: "https://spring.io/projects/spring-data",
    translation: { en: "Spring Data" },
  },
  spring_security: {
    id: "spring_security",
    type: "library",
    link: "https://spring.io/projects/spring-security",
    translation: { en: "Spring Security" },
  },
  spring_cloud: {
    id: "spring_cloud",
    type: "library",
    link: "https://spring.io/projects/spring-cloud",
    translation: { en: "Spring Cloud" },
  },
  spring_mvc: {
    id: "spring_mvc",
    type: "library",
    link: "https://spring.io/guides/gs/serving-web-content/",
    translation: { en: "Spring MVC" },
  },
  spring_webflux: {
    id: "spring_webflux",
    type: "library",
    link: "https://docs.spring.io/spring-framework/reference/web/webflux.html",
    translation: { en: "Spring WebFlux" },
  },
  lombok: {
    id: "lombok",
    type: "library",
    link: "https://projectlombok.org/",
    translation: { en: "Project Lombok" },
  },
  pandas: {
    id: "pandas",
    type: "library",
    link: "https://pandas.pydata.org/",
    translation: { en: "Pandas" },
  },
  py_spark: {
    id: "py_spark",
    type: "library",
    link: "https://spark.apache.org/docs/latest/api/python/",
    translation: { en: "PySpark" },
  },
  py_torch: {
    id: "py_torch",
    type: "library",
    link: "https://pytorch.org/",
    translation: { en: "PyTorch" },
  },
  scikit_learn: {
    id: "scikit_learn",
    type: "library",
    link: "https://scikit-learn.org/stable/",
    translation: { en: "Scikit-learn" },
  },
  keras: {
    id: "keras",
    type: "library",
    link: "https://keras.io/",
    translation: { en: "Keras" },
  },
  num_py: {
    id: "num_py",
    type: "library",
    link: "https://numpy.org/",
    translation: { en: "NumPy" },
  },
  matplotlib: {
    id: "matplotlib",
    type: "library",
    link: "https://matplotlib.org/",
    translation: { en: "Matplotlib" },
  },
  tailwind: {
    id: "tailwind",
    type: "library",
    link: "https://tailwindcss.com/",
    translation: { en: "Tailwind CSS" },
  },
  expressive_code: {
    id: "expressive_code",
    type: "library",
    link: "https://expressive-code.com/",
    translation: { en: "Expressive Code" },
  },
  playwright: {
    id: "playwright",
    type: "library",
    link: "https://playwright.dev/",
    translation: { en: "Playwright" },
  },
  rehype: {
    id: "rehype",
    type: "library",
    link: "https://github.com/rehypejs/rehype",
    translation: { en: "Rehype" },
  },
  remark: {
    id: "remark",
    type: "library",
    link: "https://remark.js.org/",
    translation: { en: "Remark" },
  },
  deep_java_library: {
    id: "deep_java_library",
    type: "library",
    link: "https://djl.ai/",
    translation: { en: "Deep Java Library" },
  },
  open_cv: {
    id: "open_cv",
    type: "library",
    link: "https://opencv.org/",
    translation: { en: "OpenCV" },
  },
  jetbrains_exposed: {
    id: "jetbrains_exposed",
    type: "library",
    link: "https://github.com/JetBrains/Exposed",
    translation: { en: "JetBrains Exposed" },
  },
  or_tools: {
    id: "or_tools",
    type: "library",
    link: "https://developers.google.com/optimization",
    translation: { en: "OR-Tools" },
  },
  androidx: {
    id: "androidx",
    type: "library",
    link: "https://developer.android.com/jetpack/androidx",
    translation: { en: "AndroidX" },
  },
  android_material: {
    id: "android_material",
    type: "library",
    link: "https://github.com/material-components/material-components-android",
    translation: { en: "Material Components for Android" },
  },
  play_services_vision: {
    id: "play_services_vision",
    type: "library",
    link: "https://developers.google.com/android/guides/setup",
    translation: { en: "Play Services Vision" },
  },
  retrofit: {
    id: "retrofit",
    type: "library",
    link: "https://square.github.io/retrofit/",
    translation: { en: "Retrofit" },
  },
  burn: {
    id: "burn",
    type: "library",
    link: "https://burn.dev/",
    translation: { en: "Burn" },
  },
  rayon: {
    id: "rayon",
    type: "library",
    link: "https://github.com/rayon-rs/rayon",
    translation: { en: "Rayon" },
  },
  room: {
    id: "room",
    type: "library",
    link: "https://developer.android.com/training/data-storage/room",
    translation: { en: "Room" },
  },
  mongo_db: {
    id: "mongo_db",
    type: "database",
    link: "https://www.mongodb.com/",
    translation: { en: "MongoDB" },
  },
  arango_db: {
    id: "arango_db",
    type: "database",
    link: "https://www.arangodb.com",
    translation: { en: "ArangoDB" },
  },
  postgres: {
    id: "postgres",
    type: "database",
    link: "https://www.postgresql.org",
    translation: { en: "PostgreSQL" },
  },
  oracle: {
    id: "oracle",
    type: "database",
    link: "https://www.oracle.com/database/technologies/",
    translation: { en: "Oracle Database" },
  },
  mysql: {
    id: "mysql",
    type: "database",
    link: "https://www.mysql.com/",
    translation: { en: "MySQL" },
  },
  mariadb: {
    id: "mariadb",
    type: "database",
    link: "https://mariadb.org/",
    translation: { en: "MariaDB" },
  },
  sqlite: {
    id: "sqlite",
    type: "database",
    link: "https://sqlite.org/",
    translation: { en: "SQLite" },
  },
  redis: {
    id: "redis",
    type: "database",
    link: "https://redis.io/",
    translation: { en: "Redis" },
  },
  firebase: {
    id: "firebase",
    type: "database",
    link: "https://firebase.google.com/",
    translation: { en: "Firebase" },
  },
  arduino: {
    id: "arduino",
    type: "other",
    link: "https://www.arduino.cc/",
    translation: { en: "Arduino" },
  },
  raspberry_pi: {
    id: "raspberry_pi",
    type: "other",
    link: "https://www.raspberrypi.com/",
    translation: { en: "Raspberry Pi" },
  },
  driving: {
    id: "driving",
    type: "other",
    link: "https://www.gov.pl/web/gov/kategorie-prawa-jazdy",
    translation: { en: "Driving License", pl: "Prawo Jazdy" },
  },
  driving_b: {
    id: "driving_b",
    type: "other",
    link: "https://www.gov.pl/web/gov/kategorie-prawa-jazdy",
    translation: { en: "Driving License - B", pl: "Prawo Jazdy - B" },
  },
  polish: {
    id: "polish",
    type: "linguistics",
    link: "https://en.wikipedia.org/wiki/Polish_language",
    translation: { en: "Polish - native", pl: "Polski - ojczysty" },
  },
  english: {
    id: "english",
    type: "linguistics",
    link: "https://en.wikipedia.org/wiki/English_language",
    translation: { en: "English - advanced", pl: "Angielski - zaawansowany" },
  },
  russian: {
    id: "russian",
    type: "linguistics",
    link: "https://en.wikipedia.org/wiki/English_language",
    translation: { en: "Russian - basic", pl: "Rosyjski - podstawowy" },
  },
};
